### ISSUE TITLE
[Feature Request:] Apply for listing in ArtifactHub

### ISSUE THREAD

**Issue by GeiserX** [getanteon/anteon-helm-charts#6]
[ArtifactHub](https://artifacthub.io/) contains a list of all installable Helm charts supercharged with functionalities, which makes DevOps work easier. It's the de-facto tool for anyone working with Helm charts, especially appealing for SREs too.

I have searched for any `ddosify` project there but it's not listed. You will need to apply for `Official status request` and request your Helm repository to be included [here](https://github.com/artifacthub/hub/issues/new/choose)

PS: I had to manually check the default `values.yaml` file to know the details. This is cumbersome.

**Comment by GeiserX** [comment]
Additionally, having a list of parameters available here in the README would be a delight for us all, like in other projects.

**Comment by fatihbaltaci** [comment]
Hi @GeiserX, we added the parameters of the Alaz helm chart [here](https://github.com/ddosify/ddosify-helm-charts#alaz-parameters). Thanks for your suggestion. 

We will look at the ArtifactHub.

**Comment by fatihbaltaci** [comment]
Here is the ArtifactHub chart: https://artifacthub.io/packages/helm/anteon/anteon
